In [1]:
import torch

In [6]:
a = torch.ones(3)
a

tensor(1.)

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [15]:
points = torch.tensor([[1.0,4.0],[ 2.0,1.0],[ 3.0,5.0]])

In [16]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [18]:
# 用shape询问张量形状
# 会告知您张量沿每个维度的大小
points.shape

torch.Size([3, 2])

In [27]:
# 可以使用zeros函数或ones函数来初始化张量，并且以元组形式指定张量的大小：
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
# 通过索引访问张量中的单个元素
points[2,1]

tensor(0.)

In [28]:
# 访问列
points[2]

tensor([0., 0.])

In [31]:
# 用storage 查看底层存储
# 存储器的布局始终是一维的，而与可能引用它的任何张量的维数无关。
points.storage()

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.FloatStorage of size 6]

In [35]:
# 手动索引到存储
points_storage = points.storage()
points_storage[5] # points.storage()[5]

0.0